# Dutch messages file
# Author: Sander Devrieze s.devrieze@pandora.be
# Please notify me of errors or incoherencies.

::msgcat::mcset nl "Whiteboard" "Whiteboard"
::msgcat::mcset nl "%s whiteboard" "Whiteboard %s"
::msgcat::mcset nl "PolyLine" "Veelhoek"
::msgcat::mcset nl "FreeHand" "Potlood"
::msgcat::mcset nl "Move" "Verplaatsen"
::msgcat::mcset nl "Clear" "Wissen"
::msgcat::mcset nl "Color" "Kleur"
::msgcat::mcset nl "Text" "Tekst"
::msgcat::mcset nl "Text Color" "Tekstkleur"
::msgcat::mcset nl "Font" "Lettertype"
::msgcat::mcset nl "OK" "OK"
::msgcat::mcset nl "Cancel" "Annuleren"