# ukrainian messages file
# writed by levsha@jabber.net.ua. Last chnage 3.10.2006

::msgcat::mcset uk "Whiteboard" "Грифельна дошка"
::msgcat::mcset uk "%s whiteboard" "%s дошка"
::msgcat::mcset uk "PolyLine" "Ламана"
::msgcat::mcset uk "FreeHand" "Крива"
::msgcat::mcset uk "Move" "Перемістити"
::msgcat::mcset uk "Remove" "Видалити"
::msgcat::mcset uk "Clear" "Очистити"
::msgcat::mcset uk "Line color" "Колір лінії"
::msgcat::mcset uk "Text" "Текст"
::msgcat::mcset uk "Text color" "Колір тексту"
::msgcat::mcset uk "Text font" "Шрифт тексту"
::msgcat::mcset uk "Line width: " "Товщина лінії: "
::msgcat::mcset uk "OK" "Продовжити"
::msgcat::mcset uk "Cancel" "Відмінити"
