# Polish messages file for attline plugin
# Author: Irek Chmielowiec
# Contact: xmpp:irek@chrome.pl :: mailto:irek.ch@gmail.com
# Please notify me of errors or incoherencies

::msgcat::mcset pl "Attention Line chat plugin options. This plugin draws horizontal line separating read and unread messages in chat windows." "Ustawienia wtyczki separatora aktywności. Wtyczka ta wstawia wstawia poziomą linię oddzielającą przeczytane i nieprzeczytane wiadomości w rozmowie."
::msgcat::mcset pl "Plugins options." "Ustawienia wtyczek."
::msgcat::mcset pl "Remove the attention line after it was expired from its chat window." "Usuń separator nieaktywności po tym jak stracił ważność w oknie rozmowy."
::msgcat::mcset pl "Time (in milliseconds) after which unread messages in the currently active chat window are considered read and the attention line is considered expired." "Czas (w milisekundach), po którym nieprzeczytane wiadomości w aktywnym oknie rozmowy zostaną uznane za przeczytane i separator starci ważność."

