
# German messages file
# Roger Sondermann 09.09.2007

::msgcat::mcset de "Unknown presence \"%s\". Must be avail\[able\], away, xa, dnd, chat or clear\[status\]" "Unbekannte Präsenz \"%s\". Erlaubt sind avail\[able\], away, xa, dnd, chat oder clear\[status\]."
::msgcat::mcset de "Usage: \t/presence ?presence|clear\[status\]?\n \t?status message?\n or\n \t/chatpresence ?presence|clear\[status\]?\n \t?status message?\n Where presence is one of: avail\[able\], away, xa, dnd, chat.\n Special presence \"clear\[status\]\" just clears the current status.\n /thispresence is an alias for /chatpresence" "Benutzung:\t/presence ?presence|clear\[status\]?\n \t\t?Status-Nachricht?\n oder:\n \t\t/chatpresence ?presence|clear\[status\]?\n \t\t?Status-Nachricht?\n\n Wobei 'presence' eines der folgenden ist: avail\[able\], away, xa, dnd, chat.\n Die spezielle Präsenz 'clear\[status\]' setzt den derzeitigen Status zurück.\n ('/thispresence' ist ein Alias für '/chatpresence')"
