# Polish messages file for presencecmd plugin
# Author: Irek Chmielowiec
# Contact: xmpp:irek@chrome.pl :: mailto:irek.ch@gmail.com
# Please notify me of errors or incoherencies

::msgcat::mcset pl "Unknown presence \"%s\". Must be avail\[able\], away, xa, dnd, chat or clear\[status\]" \
    "Nieznany status \"%s\". Prawidłowe wartości to avail\[able\], away, xa, dnd, chat lub clear\[status\]"
::msgcat::mcset pl "Usage: \t/presence ?presence|clear\[status\]?\n\
                   \t?status message?\n\
                   or\n\
                   \t/chatpresence ?presence|clear\[status\]?\n\
                   \t?status message?\n\
                   Where presence is one of: avail\[able\], away, xa, dnd, chat.\n\
                   Special presence \"clear\[status\]\" just clears the current status.\n\
                   /thispresence is an alias for /chatpresence" \
                   "Użycie: \t/presence ?presence|clear\[status\]?\n\
                   \t?opis statusu?\n\
                   lub\n \t/chatpresence ?presence|clear\[status\]?\n\
                   \t?opis statusu?\n\
                   gdzie presence jest jednym z: avail\[able\], away, xa, dnd, chat.\n\
                   Status specjalny \"clear\[status\]\" tylko czyści aktualny status.\n\
                   /thispresence jest aliasem dla /chatpresence"

