
# German messages file
# Roger Sondermann 05.11.2007

::msgcat::mcset de "Browse"                                 "Durchsuchen"
::msgcat::mcset de "Delete"                                 "Löschen"
::msgcat::mcset de "Delete Gmail notifications, which are older than 24 hours." "Gmail-Benachrichtigungen löschen, die älter als 24 Stunden sind."
::msgcat::mcset de "Delete all messages"                    "Alle Nachrichten löschen"
::msgcat::mcset de "Delete messages older than 24 hours"    "Nachrichten löschen, die älter als 24 Stunden sind"
::msgcat::mcset de "Delete seen messages"                   "Gelesene Nachrichten löschen"
::msgcat::mcset de "Format of timestamp in Gmail tree view. Set to empty string if you don't want to see timestamps." "Format des Zeitstempels in der Gmail-Baumansicht (frei lassen, wenn keine Zeitstempel angezeigt werden sollen)."
::msgcat::mcset de "Gmail"                                  "Gmail"
::msgcat::mcset de "Gmail notifications"                    "Gmail-Benachrichtigungen"
::msgcat::mcset de "Google Talk XMPP extensions."           "Google Talk XMPP-Erweiterungen."
::msgcat::mcset de "Last Gmail message time."               "Zeit der letzten Gmail-Nachricht."
::msgcat::mcset de "Mark all seen"                          "Alle Gelesenen markieren"
::msgcat::mcset de "Mark all unseen"                        "Alle Ungelesenen markieren"
::msgcat::mcset de "Mark seen"                              "Gelesene markieren"
::msgcat::mcset de "Mark unseen"                            "Ungelesene markieren"
::msgcat::mcset de "Open Gmail notifications"               "Gmail-Benachrichtigungen"
::msgcat::mcset de "Plugins options."                       "Optionen für Plugins."
::msgcat::mcset de "Request Gmail notifications."           "Gmail-Benachrichtigungen abfragen."
