# Polish messages file for gmail plugin
# Author: Irek Chmielowiec
# Contact: xmpp:irek@chrome.pl :: mailto:irek.ch@gmail.com
# Please notify me of errors or incoherencies

::msgcat::mcset pl "Browse" "Przeglądaj"
::msgcat::mcset pl "Delete" "Usuń"
::msgcat::mcset pl "Delete Gmail notifications, which are older than 24 hours." \
    "Usuwaj powiadomienia Gmail starsze niż 24 godziny."
::msgcat::mcset pl "Delete all messages" "Usuń wszystkie wiadomości"
::msgcat::mcset pl "Delete messages older than 24 hours" "Usuń wszystkie wiadomości starsze niż 24 godziny"
::msgcat::mcset pl "Delete seen messages" "Usuń przeczytane wiadomości"
::msgcat::mcset pl "Format of timestamp in Gmail tree view. Set to empty string if you don't want to see timestamps." \
    "Format znacznika czasu w widoku wiadomości Gmail. Aby wyłączyć znaczniki czasu pozostaw to pole puste."
::msgcat::mcset pl "Gmail" "Gmail"
::msgcat::mcset pl "Gmail notifications" "Powiadomienia Gmail"
::msgcat::mcset pl "Google Talk XMPP extensions." "Rozszerzenia XMPP dla Google Talk."
::msgcat::mcset pl "Last Gmail message time." "Czas ostatniego powiadomienia Gmail."
::msgcat::mcset pl "Mark all seen" "Oznacz wszystkie jako przeczytane"
::msgcat::mcset pl "Mark all unseen" "Oznacz wszystkie jako nieprzeczytane"
::msgcat::mcset pl "Mark seen" "Oznacz jako przeczytane"
::msgcat::mcset pl "Mark unseen" "Oznacz jako nieprzeczytane"
::msgcat::mcset pl "Open Gmail notifications" "Pokaż okno powiadomień Gmail"
::msgcat::mcset pl "Plugins options." "Ustawienia wtyczek."
::msgcat::mcset pl "Request Gmail notifications." "Odbieraj powiadomienia Gmail."