# $Id: ru.msg 1224 2007-09-05 14:15:40Z sergei $

::msgcat::mcset ru "Browse" "Просмотреть"
::msgcat::mcset ru "Delete" "Удалить"
::msgcat::mcset ru "Delete Gmail notifications, which are older than 24 hours." \
    "Удалять уведомления Gmail старше 24 часов."
::msgcat::mcset ru "Delete all messages" "Удалить все сообщения"
::msgcat::mcset ru "Delete messages older than 24 hours" "Удалить сообщения старше 24 часов"
::msgcat::mcset ru "Delete seen messages" "Удалить просмотренные сообщения"
::msgcat::mcset ru "Format of timestamp in Gmail tree view. Set to empty string if you don't want to see timestamps." \
    "Формат вывода даты/времени в окне уведомлений Gmail. Для того, чтобы не показывать дату/время совсем, установите эту опцию в пустую строку."
::msgcat::mcset ru "Gmail"
::msgcat::mcset ru "Gmail notifications" "Уведомления Gmail"
::msgcat::mcset ru "Google Talk XMPP extensions." "Расширения XMPP для Google Talk."
::msgcat::mcset ru "Last Gmail message time." "Время последнего сообщения Gmail."
::msgcat::mcset ru "Mark all seen" "Пометить все как просмотренные"
::msgcat::mcset ru "Mark all unseen" "Пометить все как непросмотренные"
::msgcat::mcset ru "Mark seen"
::msgcat::mcset ru "Mark unseen"
::msgcat::mcset ru "Mark seen" "Пометить как просмотренное"
::msgcat::mcset ru "Mark unseen" "Пометить как непросмотренное"
::msgcat::mcset ru "Open Gmail notifications" "Открыть окно уведомлений Gmail"
::msgcat::mcset ru "Plugins options." "Настройки расширений."
::msgcat::mcset ru "Request Gmail notifications." "Запрашивать уведомления Gmail."

