# Polish messages file for whiteboard plugin
# Author: Irek Chmielowiec
# Contact: xmpp:irek@chrome.pl :: mailto:irek.ch@gmail.com
# Please notify me of errors or incoherencies

::msgcat::mcset pl "Whiteboard" "Tablica rysunkowa"
::msgcat::mcset pl "%s whiteboard" "Tablica: %s"
::msgcat::mcset pl "PolyLine" "Linia prosta"
::msgcat::mcset pl "FreeHand" "Linia odręczna"
::msgcat::mcset pl "Move" "Przesuń"
::msgcat::mcset pl "Text" "Tekst"
::msgcat::mcset pl "Text color" "Kolor tekstu"
::msgcat::mcset pl "Text font" "Czcionka tekstu"
::msgcat::mcset pl "Line width: " "Grubość linii: "
::msgcat::mcset pl "Line color" "Kolor linii"
::msgcat::mcset pl "Cancel" "Anuluj"
::msgcat::mcset pl "Clear" "Wyczyść"
::msgcat::mcset pl "OK" "OK"
::msgcat::mcset pl "Remove" "Usuń"
::msgcat::mcset pl "Circle" "Okrąg"
::msgcat::mcset pl "Fill" "Wypełnienie"
::msgcat::mcset pl "Fill color" "Kolor wypełnienia"
::msgcat::mcset pl "Polygon" "Wielokąt"
::msgcat::mcset pl "Save..." "Zapisz..."
::msgcat::mcset pl "%s created: %s" "%s utworzył: %s"
::msgcat::mcset pl "%s moved: %s" "%s przesunął: %s"
::msgcat::mcset pl "Enter text" "Wprowadź tekst"
::msgcat::mcset pl "Show balloons" "Pokaż dymki podpowiedzi"