::msgcat::mcset ru \
    "Attention Line chat plugin options. This plugin draws horizontal\
     line separating read and unread messages in chat windows." \
    "Настройки расширения Attention Line. Это расширение отделяет непрочитанные\
     сообщения в окнах разговора от прочитанных горизонтальной линией."
::msgcat::mcset ru "Plugins options." "Параметры расширений."
::msgcat::mcset ru "Remove the attention line after it was expired from its chat window." \
    "Удалять линию, разделяющую сообщения по истечении времени её действия."
::msgcat::mcset ru \
    "Time (in milliseconds) after which unread messages in the currently\
     active chat window are considered read and the attention line is considered expired." \
    "Время (в миллисекундах) по истечении которого сообщения в активном окне разговора\
     считаются прочитанными, и разделительная линия считается недействующей."
